action_id: trunk-upgrade-available
date: 2024-04-13 00:46:53
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1712969213
full_timestamp:
  nanos: 375654000
  seconds: 1712969213
trunk_version: 1.21.0
