action_id: trunk-share-with-everyone
date: 2024-04-13 00:42:42
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1712968962
full_timestamp:
  nanos: 3416000
  seconds: 1712968962
trunk_version: 1.21.0
